// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClMCn0Z_yTiLn8xRO_xI17E4LafJmSzgU',
    appId: '1:728851422286:web:9046af17d5c72b28bf371f',
    messagingSenderId: '728851422286',
    projectId: 'zomatoproject-89021',
    authDomain: 'zomatoproject-89021.firebaseapp.com',
    storageBucket: 'zomatoproject-89021.appspot.com',
    measurementId: 'G-52FFG0SQFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5fWlVBbBvWkpm8AQRB68ZeGXN1VT33dw',
    appId: '1:728851422286:android:2259f8e906b248aebf371f',
    messagingSenderId: '728851422286',
    projectId: 'zomatoproject-89021',
    storageBucket: 'zomatoproject-89021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHy8_-HFtwVZoPD8in9Its-OO4BqrdfvM',
    appId: '1:728851422286:ios:fc74353af9d14d1abf371f',
    messagingSenderId: '728851422286',
    projectId: 'zomatoproject-89021',
    storageBucket: 'zomatoproject-89021.appspot.com',
    iosClientId:
        '728851422286-u20uafiq7lcj8q7strj0k10n6qib6u2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.zomatoProject',
  );
}
